# Generated by Django 5.1.4 on 2025-01-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='https://freesvg.org/img/Website-No-Image-Icon.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='articles.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='base_tag', max_length=100, unique=True),
        ),
    ]
