# Generated by Django 5.1.4 on 2025-01-16 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 11, 40, 9, 936894)),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='NEW'),
        ),
    ]
